apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-producer
  template:
    metadata:
      labels:
        app: redis-producer
    spec:
      containers:
        - name: redis-consumer
          image: <enter AWS account ID>.dkr.ecr.<enter AWS region>.amazonaws.com/redis-producer-app:latest
          imagePullPolicy: Always
          env:
            - name: MEMORYDB_ENDPOINT
              value: <enter MemoryDB endpoint>
            - name: MEMORYDB_USERNAME
              value: <enter MemoryDB username>
            - name: MEMORYDB_PASSWORD
              value: <enter MemoryDB password>
            - name: LIST_NAME
              value: <enter name of Redis List>
